### ISSUE TITLE
Ajouter le jeu sur le Front

### ISSUE THREAD

**Issue by restray** [restray/ft_transcendance#12]
Le jeu constitue la partie principale du projet, il ne doit pas etre sujet a quelconques erreurs et doit reproduire le [pong officiel de 1972](https://fr.wikipedia.org/wiki/Pong).

Pour la partie jeu:
 - [ ] La zone de jeu doit etre de 1.280px de large × 960 px de hauteur
 - [ ] Les raquettes des joueurs ne doivent pas aller jusqu'en haut (`Une autre problématique est que les raquettes ne vont pas jusqu'en haut de l'écran à la suite d'un défaut dans le circuit, ce qu'Alcorn ne modifie pas finalement, afin d'éviter que les parties ne durent indéfiniment`)
 - [ ] La balle augmente de vitesse des qu'elle tape une raquette
 - [ ] La raquette est composee de **8 segments differents**
    - [ ] les **2 seg du milieu** doivent renvoyer la balle a `180 deg` (la direction opposee)
    - [ ] Les **2 seg les plus eloignes** doivent renvoyer la balle a `45 deg`
 - [ ] Quand la balle touche un mur avec un angle `x`, elle doit changer de direction: `direction = 2*x`
 - [ ] La balle doit etre remise au milieu a chaque point marque.
 - [ ] Pour que la balle soit lance: les deux joueurs doivent appuyer sur `espaces`
 - [ ] Un joueur AFK > 20 sec doit etre deconnecte et le joueur adverse gagne le match

**Comment by oel-ahma** [comment]
Normalement la partie jeu et prete
