### ISSUE TITLE
(feat): destruction of a channel must trigger an event of leave to all users of this channel

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#25]

**Comment by restray** [comment]
L'evenement `delete` est cense etre trigger sur la socket channels avec le channel id en payload!

N.B. : https://github.com/restray/ft_transcendance/blob/ba58d892bc633da91c16797421663d923c5a6ce4/backend/src/messages/channels.gateway.ts#L207

duplicate
