### ISSUE TITLE
Channel image

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#35]
De la meme maniere qu'un utilisateur, ajouter une image editable aux channels

**Comment by restray** [comment]
[https://ui-avatars.com/api/?name=Un+Serveur](https://ui-avatars.com/api/?name=Un+Serveur)
![https://ui-avatars.com/api/?name=Un+Serveur](https://ui-avatars.com/api/?name=Un+Serveur)

L'API qui permet de générer des images de channels: https://ui-avatars.com/

J'ai vraiment la flemme de refaire une gestion des images, des tests, etc... Juste pour embellir une partie sur laquelle le correcteur va passer 3min.
