### ISSUE TITLE
Error 500 avec un payload invalide pour la route 'POST /channels/{id}/join Rejoindre un channel' au lieu de 400

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#36]

**Comment by restray** [comment]
Tu pourrais me donner le payload que t'envoie et la réponse donnée par le serveur? Là c'est très imprécis...

**Comment by xGoldaxe** [comment]
un objet vide

**Comment by restray** [comment]
T'as un payload à me donner? Parce que je ne pourrai pas reproduire l'erreur là :-/
