### ISSUE TITLE
Ban an user must not trigger a 'leave' event, since the user stay in the room

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#37]

**Comment by restray** [comment]
L'utilisateur n'est plus dans le channel. Le serveur le garde en tant que tel, mais ce n'est pas vrai.
L'utilisateur ne peut pas voir les messages, ne peut pas en envoyer, ni même rejoindre, ou quitter ce channel.

L'evenement `leave` est volontairement trigger sur les bans et les kicks, pour informer tous les utilisateurs, que qq1 a quitté le channel (sans spécifier le bannissement de l'utilisateur).
