### ISSUE TITLE
Admin must be able to promote other admin

### ISSUE THREAD

**Issue by xGoldaxe** [restray/ft_transcendance#38]

**Comment by xGoldaxe** [comment]
les admins peuvent pas mute ou ban non plus

**Comment by restray** [comment]
Nope, les admins ne peuvent pas nommer d'autres admins, au même titre que des modérateurs ne peuvent pas nommer des modérateurs...

**Comment by restray** [comment]
> les admins peuvent pas mute ou ban non plus

Je check ça
