### ISSUE TITLE
Game: need to receive paddle positions and score

### ISSUE THREAD

**Issue by oel-ahma** [restray/ft_transcendance#58]
Je recois que les infos sur la ball et pas la position et le score aussi @restray

**Comment by restray** [comment]
Est-ce que tu pourrais m'envoyer comment tu récupères la balle s'il te plaît ?

**Comment by oel-ahma** [comment]
![Screenshot from 2022-08-17 14-33-53](https://user-images.githubusercontent.com/52109167/185124887-63fb5251-800f-46b7-b2be-52b81ed5f5d4.png)
![Screenshot from 2022-08-17 14-32-50](https://user-images.githubusercontent.com/52109167/185124897-cdaaae6c-b2d4-4938-a08a-cd92965795ee.png)

**Comment by restray** [comment]
duplicate #55
